spring:
  application:
    name: springreview
# Configuração do banco de dados
  datasource:
    url: jdbc:mysql://localhost:3306/person?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
# Configuração do JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  # Configuração de log
  logging:
    level:
      # Nivel Global de Log
      root: INFO
      # Nivel de Log para package especifico
      #br.com.nelsonssoares.springreview: DEBUG
