file:
  upload-dir: C:\Users\Nelson\OneDrive\Área de Trabalho\Projetos\SpringBoot\springreview\files
  download-dir: C:\Users\Nelson\Downloads
  max-file-size: 200MB
  max-request-size: 215MB

cors:
  originsPatterns: http://localhost:8080 , http://localhost:4200

spring:
  application:
    name: springreview

  # Configuração do banco de dados
  datasource:
    url: jdbc:mysql://localhost:3306/person?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Configuração do JPA
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Configuração para download e upload do arquivo
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 200MB
      max-request-size: 215MB

  # Configuração de log
  logging:
    level:
    # root: INFO
    # br.com.nelsonssoares.springreview: DEBUG

  # Configuração do Swagger
  spring-doc:
    paths-to-match: /api/**/v1/**
    swagger-ui:
      use-root-path: true
    # version: 1.0
    # title: Spring Review
    # description: Documentação da API Spring Review
    # contact:
    #   name: Nelson Soares
    #   email:
    #   url: https://nelsonssoares.com
